version: '2'

services:
  vpn:
    build: "./"
    restart: always
    env_file:
      - ./vpn.env
    network_mode: "host"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro
